Sabrina/dev
fullstorydev/fullstory-segment-middleware-ios pull request #11
Opened 2020-09-24 20:35 UTC by sabrina-li

Re-structuring the project by creating a project and then integrate pod, this shared the scheme in the project rather than in pod project, so we can support both cocoapods and carthage
Let me know if this makes more sense.

2020-12-22 19:24 UTC, nvzqz requested changes
I think this makes the project easier to work with and inspect as an outsider. Good job!

I left some comments/suggestions on things I think could be improved.

2020-12-22 19:24 UTC, nvzqz commented on FullStorySegmentMiddleware.podspec
> +  spec.summary      = "FullStory Segment Middleware is a project demonstrating the full potential of joining forces between Segment + FullStory."
I think the summary should be a bit shorter.
```suggestion
  spec.summary      = "Demonstrates the full potential of joining forces between Segment and FullStory."
```

2020-12-22 19:24 UTC, nvzqz commented on FullStorySegmentMiddleware.podspec
> +  FullStory Segment Middleware is a project demonstrating the full potential of joining forces between Segment + FullStory.
Likewise I think the description should be shorter.

```suggestion
  This demonstrates the full potential of joining forces between Segment and FullStory.
```

2020-12-22 19:24 UTC, nvzqz commented on FullStorySegmentMiddleware.podspec
> +  # spec.screenshots  = "www.example.com/screenshots_1.gif", "www.example.com/screenshots_2.gif"
I would just remove this line.

2020-12-22 19:24 UTC, nvzqz commented on FullStorySegmentMiddleware.podspec
> +  spec.platform     = :ios, "8.0"
```suggestion
  spec.platform     = :ios, "8.0"
```

2020-12-22 19:24 UTC, nvzqz commented on FullStoryMiddleware/FullStoryMiddleware.h
>  @property (strong, nonatomic) NSArray* allowlistEvents;
While we're restructuring the project...
```suggestion
@property (strong, nonatomic) NSArray<NSString *>* allowlistEvents;
```

2020-12-22 19:24 UTC, nvzqz commented on FullStoryMiddlewareExample/main.m
> +    }
This autorelease pool isn't necessary.

2020-12-22 19:24 UTC, nvzqz commented on Podfile
> +end
I would sort these in order of relevance.

```suggestion
target 'FullStoryMiddleware' do
  common_pods
end

target 'FullStoryMiddlewareExample' do
  common_pods
  pod 'FullStorySegmentMiddleware', :path => '.'
end

target 'FullStoryMiddlewareTests' do
  common_pods
  pod 'OCMock', '~>3.6'
end
```

2020-12-22 21:00 UTC, sabrina-li commented on FullStoryMiddlewareExample/main.m
> +    }
removed

2020-12-22 21:00 UTC, sabrina-li commented on FullStorySegmentMiddleware.podspec
> +  # spec.screenshots  = "www.example.com/screenshots_1.gif", "www.example.com/screenshots_2.gif"
removed

2020-12-22 21:01 UTC, sabrina-li commented
> I think this makes the project easier to work with and inspect as an outsider. Good job!
> 
> I left some comments/suggestions on things I think could be improved.

Thanks so much for the detailed review!! updated. please give this another go :)

2020-12-22 22:54 UTC, nvzqz requested changes
Thanks for making the requested changes! Although you accidentally removed some important code while doing so.

2020-12-22 22:54 UTC, nvzqz commented on FullStoryMiddlewareExample/main.m
> +    NSString * appDelegateClassName;
You removed the autorelease pool, but you also removed getting the name of the app delegate's class.
```suggestion
    NSString * appDelegateClassName = NSStringFromClass([AppDelegate class]);
```

2020-12-23 00:56 UTC, nvzqz approved these changes
🚢 it

2020-12-23 16:47 UTC, merged